// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRD7GwL6AV24xI1emlDG1gXxdcax1o6E',
    appId: '1:768563455890:web:eb29e6046cb1bd869e434b',
    messagingSenderId: '768563455890',
    projectId: 'myoceanapp-75531',
    authDomain: 'myoceanapp-75531.firebaseapp.com',
    storageBucket: 'myoceanapp-75531.firebasestorage.app',
    measurementId: 'G-B22H6WCGKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApD97tiPJN7D_yqVIVtqz6ry-AQ5svjwU',
    appId: '1:768563455890:android:371422f38dca58509e434b',
    messagingSenderId: '768563455890',
    projectId: 'myoceanapp-75531',
    storageBucket: 'myoceanapp-75531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSmlU9gKtW2MSKQj70VxmoNGKQuKHiMfc',
    appId: '1:768563455890:ios:69bd80e14683dd889e434b',
    messagingSenderId: '768563455890',
    projectId: 'myoceanapp-75531',
    storageBucket: 'myoceanapp-75531.firebasestorage.app',
    iosBundleId: 'com.example.myoceanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSmlU9gKtW2MSKQj70VxmoNGKQuKHiMfc',
    appId: '1:768563455890:ios:69bd80e14683dd889e434b',
    messagingSenderId: '768563455890',
    projectId: 'myoceanapp-75531',
    storageBucket: 'myoceanapp-75531.firebasestorage.app',
    iosBundleId: 'com.example.myoceanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDRD7GwL6AV24xI1emlDG1gXxdcax1o6E',
    appId: '1:768563455890:web:69c15531afd077ce9e434b',
    messagingSenderId: '768563455890',
    projectId: 'myoceanapp-75531',
    authDomain: 'myoceanapp-75531.firebaseapp.com',
    storageBucket: 'myoceanapp-75531.firebasestorage.app',
    measurementId: 'G-9YBN4N660W',
  );
}
